name: build-docs

on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Build API docs
        run: npm run docs || true
      - name: Commit any changes back to the PR
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update API docs
          file_pattern: "docs/api/**/*"
