name: Lint

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  run-bsc:
    name: Run brightsripter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

#       - name: Install Node.js dependencies
#         run: yarn install --frozen-lockfile
#         env:
#           SKIP_PREPARE: true
          
      - name: Install brighterscript
        run: npm install -g brighterscript

      - name: Lint with brighterscript
        run: bsc --create-package false --copy-to-staging false
